In [20]:
from numpy.linalg import svd
import numpy as np

In [25]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [26]:
U, S, V = svd(data)

In [30]:
U

array([[-0.09654784, -0.76855612,  0.60364209,  0.1183155 ,  0.14702948],
       [-0.24551564, -0.4896142 , -0.58205057, -0.58459048,  0.13953892],
       [-0.39448345, -0.21067228, -0.45136196,  0.76266542, -0.12088773],
       [-0.54345125,  0.06826963,  0.23430725, -0.24482139, -0.76495921],
       [-0.69241905,  0.34721155,  0.19546318, -0.05156905,  0.59927855]])

In [19]:
S

array([3.86226568e+01, 2.07132307e+00, 7.60977226e-16, 3.86063773e-16])

In [11]:
V

array([[-0.4284124 , -0.47437252, -0.52033264, -0.56629275],
       [ 0.71865348,  0.27380781, -0.17103786, -0.61588352],
       [ 0.28255951, -0.72647617,  0.6052738 , -0.16135714],
       [-0.46921223,  0.41500889,  0.57761893, -0.52341558]])

In [27]:
k = 2
U_k = U[:,:k]
S_k = np.diag(S[:k])
V_k = V[:k,:]

reconstructed_data = U_k.dot(S_k).dot(V_k)
reconstructed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])